kind: Deployment
apiVersion: apps/v1
metadata:
  name: nu-address-book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nu-address-book
  template:
    metadata:
      labels:
        app: nu-address-book
    spec:
      containers:
        - name: nu-address-book
          image: amourycodes/nu-address-book
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: nu-address-book
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: nu-address-book
